[package]
name = "risc0-zkvm-methods"
version = { workspace = true }
edition = { workspace = true }

[build-dependencies]
risc0-build = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[package.metadata.release]
release = false

[package.metadata.risc0]
methods = ["guest", "rand", "std", "cpp-crates"]

[dependencies]
risc0-zkvm = { workspace = true }
risc0-zkvm-platform = { workspace = true }
serde = { version = "1.0", default-features = false, features = ["derive"] }
