[package]
name = "wordle"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
risc0-zkvm = { path = "../../risc0/zkvm" }
wordle-core = { path = "core" }
wordle-methods = { path = "methods" }

[dev-dependencies]
serial_test = "3.1"

[features]
cuda = ["risc0-zkvm/cuda"]
default = []
metal = ["risc0-zkvm/metal"]
prove = ["risc0-zkvm/prove"]
