[package]
name = "zkevm-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
ethers-core = "2.0"
ethers-providers = "2.0"
risc0-zkvm = { path = "../../risc0/zkvm" }
tokio = "1"
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
zkevm-core = { path = "core", features = ["ethers"] }
zkevm-methods = { path = "methods" }

[features]
cuda = ["risc0-zkvm/cuda"]
default = []
metal = ["risc0-zkvm/metal"]
prove = ["risc0-zkvm/prove"]
