[package]
name = "risc0-zkvm"
description = "RISC Zero zero-knowledge VM"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[[bench]]
name = "fib"
harness = false
required-features = ["prove"]

[[bench]]
name = "guest_run"
harness = false

[[example]]
name = "datasheet"
required-features = ["prove"]

[[example]]
name = "fib"
required-features = ["prove"]

[[example]]
name = "loop"
required-features = ["prove"]

[[example]]
name = "recursion"
required-features = ["prove"]

[dependencies]
anyhow = { version = "1.0", default-features = false }
bytemuck = { version = "1.13", features = ["extern_crate_alloc"] }
cfg-if = "1.0"
getrandom = { version = "0.2", features = ["custom"] }
hex = { version = "0.4.3", default-features = false, features = ["alloc"] }
risc0-binfmt = { workspace = true }
risc0-circuit-recursion = { workspace = true }
risc0-circuit-rv32im = { workspace = true }
risc0-core = { workspace = true }
risc0-groth16 = { workspace = true }
risc0-zkp = { workspace = true }
risc0-zkvm-platform = { workspace = true, features = [
  "rust-runtime",
  "export-getrandom",
] }
rrs-lib = "0.1"
semver = { version = "1.0", default-features = false }
serde = { version = "1.0", default-features = false, features = [
  "alloc",
  "derive",
] }
tracing = { version = "0.1", default-features = false, features = [
  "attributes",
] }

# Host dependencies
[target.'cfg(not(target_os = "zkvm"))'.dependencies]
addr2line = { version = "0.22", features = ["rustc-demangle"], optional = true }
bincode = { version = "1.3", optional = true }
bonsai-sdk = { workspace = true, optional = true }
bytes = { version = "1.4", features = ["serde"], optional = true }
elf = { version = "0.7", default-features = false, optional = true }
lazy-regex = { version = "3.1", optional = true }
nvtx = { version = "1.3", optional = true }
prost = { version = "0.12", optional = true }
rand = { version = "0.8", optional = true }
rayon = { version = "1.5", optional = true }
rustc-demangle = { version = "0.1", optional = true }
sha2 = { version = "0.10", default-features = false }
tempfile = { version = "3", optional = true }
typetag = { version = "0.2", optional = true }

[dev-dependencies]
clap = { version = "4.5", features = ["derive"] }
criterion = { version = "0.5", features = ["html_reports"] }
rand = "0.8"
tracing-forest = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[target.'cfg(not(target_os = "zkvm"))'.dev-dependencies]
crypto-bigint = { version = "0.5", default-features = false, features = [
  "rand",
] }
enum-iterator = "2.1"
flate2 = "1.0"
hotbench = { workspace = true }
human-repr = { version = "1.0", features = ["1024"] }
risc0-zkvm-methods = { path = "methods" }
serde_json = "1.0"
serde_with = "3.8"
tabled = "0.15"
tar = "0.4"
tempfile = "3"
test-log = { version = "0.2", default-features = false, features = ["trace"] }

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
# NOTE: cuda and metal are excluded because their build scripts require external tools.
features = ["client", "prove", "getrandom", "std"]

[features]
client = [
  "dep:bincode",
  "dep:bonsai-sdk",
  "dep:bytes",
  "dep:prost",
  "dep:tempfile",
  "std",
]
cuda = [
  "prove",
  "risc0-circuit-recursion/cuda",
  "risc0-circuit-rv32im/cuda",
  "risc0-zkp/cuda",
]
dual = []
metal = [
  "prove",
  "risc0-circuit-recursion/metal",
  "risc0-circuit-rv32im/metal",
  "risc0-zkp/metal",
]
default = ["client"]
disable-dev-mode = []
# This flag uses the docker environment to build test guests such as multi-test
# to ensure accurate cycle and segment counts. Tests that have been gated on
# this flag measure cycles and segments. Without this flag, the rust build
# system will generate binaries that not identical across all architectures.
# While this is acceptable for most tests, the tests counting cycles and
# segments will fail intermittently. It does not effect non-test code.
docker = []
# The zkVM exposes a getrandom implementation that panics by default. This will
# expose a getrandom implementation that uses the `sys_random` ecall.
getrandom = ["risc0-zkvm-platform/getrandom"]
prove = [
  "client",
  "dep:addr2line",
  "dep:bincode",
  "dep:bytes",
  "dep:elf",
  "dep:lazy-regex",
  "dep:nvtx",
  "dep:prost",
  "dep:rand",
  "dep:rayon",
  "dep:rustc-demangle",
  "dep:tempfile",
  "dep:typetag",
  "risc0-circuit-recursion/prove",
  "risc0-circuit-rv32im/prove",
  "risc0-groth16/prove",
  "risc0-zkp/prove",
  "std",
]
seq = ["risc0-circuit-rv32im/seq"]
std = [
  "anyhow/std",
  "hex/std",
  "risc0-binfmt/std",
  "risc0-groth16/std",
  "risc0-zkp/std",
  "serde/std",
  "sha2/std",
]
