[package]
name = "doc-test"
version = "0.1.0"
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[package.metadata.release]
release = false

[dependencies]
anyhow = "1.0"
risc0-zkvm = { workspace = true, features = ["prove"] }
risc0-zkvm-methods = { path = "../../../risc0/zkvm/methods" }
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
glob = "0.3"
