action_id: trunk-upgrade-available
date: 2024-08-10 21:19:00
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1723324740
full_timestamp:
  nanos: 238786000
  seconds: 1723324740
trunk_version: 1.22.2
